# Creating arrays

In [1]:
#import numpy library
import numpy as np

arr = np.array([1, 2, 3, 4])

In [2]:
print(arr)

[1 2 3 4]


In [3]:
#0-D arrays
arr_0d = np.array(7)

print(arr_0d)

7


In [4]:
#1-D arrays
arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)

[1 2 3 4 5]


In [13]:
#2-D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
#3-D arrays
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
print(arr.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [9]:
#an array with 5 dimensions
arr_5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr_5d)
print('number of dimensions :', arr_5d.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Indexing

In [11]:
print(arr[0])

1


In [12]:
print(arr[2] + arr[3])

7


In [17]:
#access elements from 2-D arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [18]:
#access elements from 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# Array Slicing

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


# Data Types

In [27]:
arr = np.array([1, 2, 3, 4])

print(type(arr))
print(arr.dtype)


<class 'numpy.ndarray'>
int64


In [28]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [29]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [39]:
# arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[[[[[ True  True  True  True]]]]]
bool


# Copy and View

In [40]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# Array Shape

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [38]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Iterating Arrays

In [44]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


# Joining Array

In [46]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [53]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


# Splitting Array

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Searching Arrays

In [59]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [61]:
arr = np.array([1, 2, 3, 4, 10, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 4, 5, 7]),)


In [69]:
arr = np.array([6, 7, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [70]:
y = np.searchsorted(arr, 7, side='right')

print(y)

3


# Sorting Arrays

In [71]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [72]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filter Array

In [73]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [74]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(arr)
print(filter_arr)
print(newarr)

[41 42 43 44]
[False, False, True, True]
[43 44]
