In [1]:
#Import Numpy as np
import numpy as np

In [2]:
#Create a 1D array of numbers from 0 to 9
arr_0_9 = np.arange(10)
print(arr_0_9)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Create a 3×3 numpy array of all True’s
arr_trues = np.full((3,3), True, dtype=bool)
print(arr_trues)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#Extract all odd numbers
arr2 = np.array([0, 1,2,5,4,6,7,89,76,90,99,77])
arr_odds = arr2[arr2%2 == 1]
print(arr_odds)

[ 1  5  7 89 99 77]


In [12]:
#Replace all odd numbers in arr with -1
arr_odds[arr_odds%2==1] = -1
print(arr_odds)

[-1 -1 -1 -1 -1 -1]


In [13]:
#Replace all odd numbers in arr with -1 without changing
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
#Convert a 1D array to a 2D array with 2 rows
arr = np.arange(12)
arr = arr.reshape(3,-1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
#et the common items between arr1 and arr2
arr1 = np.array([1,2,3,2,3,4,3,4,5,6,67])
arr2 = np.array([7,2,10,2,67,7,4,9,4,9,8])
print(np.intersect1d(arr1,arr2))


[ 2  4 67]


In [24]:
#From array arr1 remove all items present in array arr2
print(np.setdiff1d(arr1,arr2))

[1 3 5 6]


In [25]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)